# rule identifiers to opt in
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newLine
  - empty_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional


# special configuration for rules 
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 5
  error: 8

implicitly_unwrapped_optional:
  mode: allExceptIBOutlets

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 120
  error: 200
  ignores_urls: false
  ignores_function_declarations: true
  ignores_comments: true

